# Generated by Django 5.2.4 on 2025-08-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(help_text='Nome do ícone (ex: fa-chart-line)', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_site', models.CharField(default='Sistema JAM - ERP Moderno', max_length=100)),
                ('subtitulo_site', models.CharField(default='O ERP mais moderno do mundo', max_length=200)),
                ('descricao_site', models.TextField(default='Sistema completo para gestão empresarial')),
                ('email_contato', models.EmailField(default='contato@sistemajam.com.br', max_length=254)),
                ('telefone_contato', models.CharField(default='(11) 99999-9999', max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('assunto', models.CharField(choices=[('vendas', 'Vendas'), ('suporte', 'Suporte'), ('parceria', 'Parceria'), ('outro', 'Outro')], max_length=20)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('respondido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='depoimentos/')),
                ('depoimento', models.TextField()),
                ('nota', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('fonte', models.CharField(default='site', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_anual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destaque', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('max_usuarios', models.IntegerField(default=1)),
                ('max_empresas', models.IntegerField(default=1)),
                ('max_produtos', models.IntegerField(default=100)),
                ('max_clientes', models.IntegerField(default=100)),
                ('tem_estoque', models.BooleanField(default=True)),
                ('tem_vendas', models.BooleanField(default=True)),
                ('tem_financeiro', models.BooleanField(default=True)),
                ('tem_ordens_servico', models.BooleanField(default=True)),
                ('tem_relatorios', models.BooleanField(default=True)),
                ('tem_ia_assistant', models.BooleanField(default=False)),
                ('tem_api', models.BooleanField(default=False)),
                ('tem_suporte_prioritario', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['ordem', 'preco_mensal'],
            },
        ),
    ]
