# Generated by Django 5.2.4 on 2025-07-28 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vendas', 'Relatório de Vendas'), ('estoque', 'Relatório de Estoque'), ('financeiro', 'Relatório Financeiro'), ('clientes', 'Relatório de Clientes'), ('os', 'Relatório de Ordens de Serviço'), ('produtos', 'Relatório de Produtos')], max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('arquivo_gerado', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
    ]
