# Generated by Django 5.2.4 on 2025-07-28 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('lojas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome_produto', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('condicao', models.CharField(choices=[('excelente', '⭐ Excelente'), ('muito_bom', '⭐⭐ Muito Bom'), ('bom', '⭐⭐⭐ Bom'), ('regular', '⭐⭐⭐⭐ Regular'), ('ruim', '⭐⭐⭐⭐⭐ Ruim')], default='bom', max_length=20)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_repasse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentual_repasse', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('status', models.CharField(choices=[('recebido', '📦 Recebido'), ('avaliado', '🔍 Em Avaliação'), ('aprovado', '✅ Aprovado'), ('em_venda', '💰 À Venda'), ('vendido', '🎉 Vendido'), ('rejeitado', '❌ Rejeitado'), ('devolvido', '↩️ Devolvido')], default='recebido', max_length=20)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_venda', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('whatsapp_cliente', models.CharField(blank=True, max_length=20)),
                ('notificar_whatsapp', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignados', to='clientes.cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignados', to='lojas.loja')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consignado',
                'verbose_name_plural': 'Consignados',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoConsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('data_mudanca', models.DateTimeField(auto_now_add=True)),
                ('consignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='consignados.consignado')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Consignado',
                'verbose_name_plural': 'Históricos de Consignados',
                'ordering': ['-data_mudanca'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True)),
                ('consignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='consignados.consignado')),
            ],
            options={
                'verbose_name': 'Notificação WhatsApp',
                'verbose_name_plural': 'Notificações WhatsApp',
                'ordering': ['-data_envio'],
            },
        ),
    ]
