# Generated by Django 5.2.4 on 2025-07-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='lojas.loja')),
            ],
        ),
    ]
