# Generated by Django 5.2.4 on 2025-08-02 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('chatbot', 'Chatbot'), ('analytics', 'Analytics Preditivo'), ('automation', 'Automação'), ('vision', 'Visão Computacional'), ('nlp', 'Processamento de Linguagem Natural')], max_length=20)),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomacaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('trigger', models.CharField(max_length=100)),
                ('acao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredicaoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vendas', 'Vendas'), ('estoque', 'Estoque'), ('financeiro', 'Financeiro'), ('clientes', 'Clientes'), ('tendencias', 'Tendências de Mercado')], max_length=20)),
                ('dados_entrada', models.JSONField()),
                ('predicao', models.JSONField()),
                ('acuracia', models.FloatField()),
                ('data_predicao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('contexto', models.JSONField(default=dict)),
                ('data_conversa', models.DateTimeField(auto_now_add=True)),
                ('assistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.aiassistant')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_conversa'],
            },
        ),
    ]
