# Generated by Django 5.2.4 on 2025-07-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('lojas', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do problema/serviço')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=50, verbose_name='Status')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number')),
                ('foto_produto', models.ImageField(blank=True, null=True, upload_to='os_fotos/', verbose_name='Foto do Produto')),
                ('termo_garantia', models.TextField(blank=True, default='O serviço realizado possui garantia de 90 dias, conforme legislação vigente, desde que o lacre e o serial estejam intactos.', null=True, verbose_name='Termo de Garantia')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordens_servico.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Item da Ordem de Serviço',
                'verbose_name_plural': 'Itens da Ordem de Serviço',
            },
        ),
        migrations.CreateModel(
            name='CheckListOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Item do Checklist')),
                ('realizado', models.BooleanField(default=False, verbose_name='Realizado')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='ordens_servico.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Checklist da Ordem de Serviço',
                'verbose_name_plural': 'Checklists das Ordens de Serviço',
            },
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', None), _negated=True), fields=('serial_number',), name='unique_serial_number_not_null'),
        ),
    ]
