# Generated by Django 5.2.4 on 2025-07-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depositos', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('deposito_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='depositos.deposito')),
                ('deposito_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_saida', to='depositos.deposito')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
