# Generated by Django 5.2.4 on 2025-08-02 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('produto', 'Visualização de Produto'), ('estoque', 'Gestão de Estoque'), ('treinamento', 'Treinamento'), ('manutencao', 'Manutenção'), ('vendas', 'Vendas')], max_length=20)),
                ('descricao', models.TextField()),
                ('modelo_3d', models.FileField(blank=True, null=True, upload_to='ar_models/')),
                ('marcador_ar', models.ImageField(blank=True, null=True, upload_to='ar_markers/')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modelo_3d', models.FileField(upload_to='ar_objects/')),
                ('textura', models.ImageField(blank=True, null=True, upload_to='ar_textures/')),
                ('escala', models.FloatField(default=1.0)),
                ('posicao_x', models.FloatField(default=0.0)),
                ('posicao_y', models.FloatField(default=0.0)),
                ('posicao_z', models.FloatField(default=0.0)),
                ('rotacao', models.JSONField(default=dict)),
                ('animacao', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SessaoAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('dados_interacao', models.JSONField(default=dict)),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_experience.experienciaar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InteracaoAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('toque', 'Toque'), ('gesto', 'Gesto'), ('voz', 'Comando de Voz'), ('movimento', 'Movimento')], max_length=20)),
                ('dados_interacao', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('objeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ar_experience.objetoar')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_experience.sessaoar')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
