# Generated by Django 5.2.4 on 2025-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(default='un', max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
